### ISSUE TITLE
Incorrect use of the word `glossary`

### ISSUE THREAD

**Issue by luca-aurelia** [AkshatM/ConsistentHashRing#1]
Hi @AkshatM,

Really enjoyed your excellent blog post on [consistent hash rings](https://akshatm.svbtle.com/consistent-hash-rings-theory-and-implementation). I noticed a small error that I think is worth correcting. Near the top of the post, you say:

> A glossary, too, is a map - given a word, it can take you to the exact page the word is referenced.

That's not quite correct. Strictly speaking, a glossary is a kind of [short dictionary](http://www.dictionary.com/browse/glossary). The maps you describe are called [concordances](https://en.wikipedia.org/wiki/Concordance_(publishing)). You can also call them [indexes](https://en.wikipedia.org/wiki/Index_(publishing)), though I think concordance is closer to what you mean.

**Comment by AkshatM** [comment]
I'm an idiot - I forgot what a glossary was, and confused it with an index, as you rightly point out. I'll make the change.

**Comment by AkshatM** [comment]
Fixed. Thanks!

**Comment by luca-aurelia** [comment]
My pleasure. Thanks for writing the post!
